### ISSUE TITLE
--application-template

### ISSUE THREAD

**Issue by youngmikee** [aws/aws-sam-cli-app-templates#121]
this is no longer path of the sam cli options

therefore sam init --runtime nodejs12.x --application-template typescript-app-template, keeps failing

**Comment by jfuss** [comment]
@youngmikee The command fails because `--application-template` is not an option for SAM CLI:
```
sam init --runtime nodejs12.x --application-template typescript-app-template
Usage: sam init [OPTIONS]
Try 'sam init -h' for help.

Error: no such option: --application-template
```

The correct option is `--app-template`.
