### ISSUE TITLE
Java 11 -> gradle -> step function appears to not be accessable from SAM cli

### ISSUE THREAD

**Issue by brian-1d3** [aws/aws-sam-cli-app-templates#122]
if I do `sam init` and select

Quick start template -> Zip -> Java 11 runtime -> Gradle -> Step functions sample app

then sam cli selects an 'EventBridge' app, displaying event bridge options:

```
Do you want to use the default AWS profile [default] and region [eu-west-1]? [Y/n]: y

Which Schema would you like to use?
	1 - aws.a4b@RoomStateChange
	2 - aws.athena@AthenaQueryStateChange
	3 - aws.autoscaling@AWSAPICallViaCloudTrail
	4 - aws.autoscaling@EC2InstanceLaunchLifecycleAction
	5 - aws.autoscaling@EC2InstanceLaunchSuccessful
	6 - aws.autoscaling@EC2InstanceLaunchUnsuccessful
	7 - aws.autoscaling@EC2InstanceTerminateLifecycleAction
	8 - aws.autoscaling@EC2InstanceTerminateSuccessful
	9 - aws.autoscaling@EC2InstanceTerminateUnsuccessful
	10 - aws.batch@AWSAPICallViaCloudTrail
```

the expected behaviour would be what happens when the the above is performed with the`java 8` runtime selected -  pulling the step-functions-app-template:

```
   Generating application:
    -----------------------
    Name: hw-step2
    Runtime: java8
    Dependency Manager: gradle
    Application Template: step-functions-sample-app
    Output Directory: .
```

**Comment by jfuss** [comment]
I was able to verify the behavior above. This is caused by https://github.com/aws/aws-sam-cli-app-templates/blob/master/manifest.json#L220. I think this is a error in the config, as none of the other `step-functions-sample-app` have this set.
