### ISSUE TITLE
Add official template for Lambda Powertools for (Python, Java, Typescript)

### ISSUE THREAD

**Issue by michaelbrewer** [aws/aws-sam-cli-app-templates#143]
It would be a great value from a productivity point of view to add a template for AWS Lambda Powertool, much like [AWS Lambda  Powertools Python](https://github.com/aws-samples/cookiecutter-aws-sam-python), [AWS Lambda  Powertools Java](https://github.com/aws-samples/cookiecutter-aws-sam-powertools-java) & [AWS Lambda Powertools Typescript](https://github.com/aws-samples/cookiecutter-aws-sam-powertools-typescript)

I would be able to contribute if this is accepted.

Currently you can do the following, but having an official one would increase discoverability:

```shell
# Java
sam init --location gh:aws-samples/cookiecutter-aws-sam-powertools-java
# Python
sam init --location gh:aws-samples/cookiecutter-aws-sam-python
```

**Comment by marksailes** [comment]
Like this?

https://github.com/aws-samples/cookiecutter-aws-sam-powertools-java

**Comment by michaelbrewer** [comment]
Yep, that is linked in the ticket.

**Comment by orozcoadrian** [comment]
In the meantime:
```shell
sam init --location gh:aws-samples/cookiecutter-aws-sam-powertools-java
```

**Comment by praneetap** [comment]
We would love this contribution!

**Comment by michaelbrewer** [comment]
sure @praneetap ! maybe have a chat to @heitorlessa and @marksailes about the existing cookie cutter templates

**Comment by michaelbrewer** [comment]
@praneetap - added the inclusion of the new typescript version to the list

**Comment by praneetap** [comment]
> @praneetap - added the inclusion of the new typescript version to the list

We are working on ESBuilder support for typescript, so typescript init template would be very helpful once we get that out 😊
