### ISSUE TITLE
Missing Makefile from go1.x template

### ISSUE THREAD

**Issue by mauleyzaola** [aws/aws-sam-cli-app-templates#149]
Hello, on this template [go1.x](https://github.com/aws/aws-sam-cli-app-templates/tree/master/go1.x-image/cookiecutter-aws-sam-hello-golang-lambda-image/%7B%7Bcookiecutter.project_name%7D%7D)

There is no `Makefile`, however document says otherwise

**Comment by hoffa** [comment]
Thanks for the heads-up; it's a remnant that shouldn't be there.
