### ISSUE TITLE
Example for Go with AL2 base

### ISSUE THREAD

**Issue by Phuurl** [aws/aws-sam-cli-app-templates#181]
The current Go examples use the `go1.x` Lambda runtime, which is [announced as being considered legacy](https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-to-al2/) as it uses Amazon Linux, and does not support newer Lambda features such as ARM/Graviton2 support. Could they either be updated to use the `provided.al2` runtime, or have a separate `provided.al2` Go example available?

It looks like there's already a SAM example for it [published by AWS](https://github.com/aws-samples/sessions-with-aws-sam/tree/master/go-al2), so it could just be a case of bringing that over to this repo and making any minor changes required to make it easily available within the `sam init` workflow.

Thanks!

**Comment by jfuss** [comment]
@Phuurl Thanks for the request. Previously, we didn't have support for provided runtimes and this has changed with our Rust examples. Happy to review a PR on adding go1.x in this manner. https://github.com/aws/aws-sam-cli-app-templates/tree/master/provided.al2 is where you should put the example.

**Comment by lucashuy** [comment]
Thanks for suggesting this request! The templates for the AL2 runtime have been merged in, stay tuned for a future release of SAM CLI to seem them in `sam init`

**Comment by sriram-mv** [comment]
New release of AWS SAM CLI should support this.
