### ISSUE TITLE
.NET 3.1 Test - mock the response in the test so that it can be invoked without any permission

### ISSUE THREAD

**Issue by ulili5** [aws/aws-sam-cli-app-templates#195]
Mock the test implementations for the .NET 3.1 S3 and Web Template

**Comment by mndeveci** [comment]
Thanks for creating this issue @ulili5 would you like to raise a PR for this?

**Comment by sleepwithcoffee** [comment]
The fact that `GetObjectMetadataResponse` has `Headers` as read-only makes mocking quite a bit tricky.
It is also evident in AWS dotnet SDK code base itself that this class is mostly used in integration tests. An internal class `GetObjectMetadataResponseUnmarshaller` can be used to achieve to purpose.

![image](https://user-images.githubusercontent.com/3896985/227880727-b9fba992-8f8a-4d5e-bb81-00ec5df97d96.png)

I think it's not beneficial to this repo to replicate the same method, I will try a lighter way to mock the S3 API response.

**Comment by jfuss** [comment]
Closing since #370 was merged and released.
