### ISSUE TITLE
Add SAM template for .NET 6 C# **Quick Start: Web Backend**

### ISSUE THREAD

**Issue by ulili5** [aws/aws-sam-cli-app-templates#196]
AWS  announced [the .NET 6 runtime for AWS Lambda](https://aws.amazon.com/blogs/compute/introducing-the-net-6-runtime-for-aws-lambda/) Let's add SAM template for .NET 6 C# **Quick Start: Web Backend**

**Comment by jfuss** [comment]
PR was merged and this will go out in the next SAM CLI release. 

Closing
