### ISSUE TITLE
Add SAM template for .NET 6 C# **Quick Start: SNS**

### ISSUE THREAD

**Issue by ulili5** [aws/aws-sam-cli-app-templates#198]
AWS announced [the .NET 6 runtime for AWS Lambda](https://aws.amazon.com/blogs/compute/introducing-the-net-6-runtime-for-aws-lambda/), let's add SAM template for .NET 6 C# **Quick Start: SNS**

**Comment by mndeveci** [comment]
Thanks for creating this issue @ulili5 would you like to raise a PR for this?

**Comment by mndeveci** [comment]
Thanks for raising this issue, we will merge PR once comments are addressed.

**Comment by mndeveci** [comment]
PR is merged, resolving this issue
