### ISSUE TITLE
Add SAM template for .NET 6 C# **Quick Start: S3**

### ISSUE THREAD

**Issue by ulili5** [aws/aws-sam-cli-app-templates#199]
AWS announced [the .NET 6 runtime for AWS Lambda](https://aws.amazon.com/blogs/compute/introducing-the-net-6-runtime-for-aws-lambda/), let's add SAM template for .NET 6 C# **Quick Start: S3**

**Comment by mndeveci** [comment]
Hi @ulili5,

We would love to review your PR if you (or your team) wants to contribute for this template.

**Comment by sleepwithcoffee** [comment]
The fact that `GetObjectMetadataResponse` has `Headers` as read-only makes mocking quite a bit tricky.
It is also evident in AWS dotnet SDK code base itself that this class is mostly used in integration tests. An internal class `GetObjectMetadataResponseUnmarshaller` can be used to achieve to purpose.

![image](https://user-images.githubusercontent.com/3896985/227880727-b9fba992-8f8a-4d5e-bb81-00ec5df97d96.png)

I think it's not beneficial to this repo to replicate the same method, I will try a lighter way to mock the S3 API response.

**Comment by hnnasit** [comment]
Closing this issue as completed since the PR mentioned above was merged and released in SAM CLI [1.80.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.80.0).
