### ISSUE TITLE
Add SAM template for .NET 6 C# **Quick Start: Scheduled Events**

### ISSUE THREAD

**Issue by ulili5** [aws/aws-sam-cli-app-templates#200]
AWS announced [the .NET 6 runtime for AWS Lambda](https://aws.amazon.com/blogs/compute/introducing-the-net-6-runtime-for-aws-lambda/), let's add SAM template for .NET 6 C# **Quick Start: Scheduled Events**

**Comment by ulili5** [comment]
#183 Work in progress

**Comment by jfuss** [comment]
PR was merged and will go out in the next SAM CLI release.

Closing.
