### ISSUE TITLE
Add SAM template for .NET 6 C# **Quick Start: From Scratch**

### ISSUE THREAD

**Issue by ulili5** [aws/aws-sam-cli-app-templates#201]
AWS announced [the .NET 6 runtime for AWS Lambda](https://aws.amazon.com/blogs/compute/introducing-the-net-6-runtime-for-aws-lambda/), let's add SAM template for .NET 6 C# **Quick Start: From Scratch**

**Comment by rjesh-git** [comment]
Assign to me!

**Comment by mingkun2020** [comment]
Thanks @ulili5 for reporting this and thanks @rjesh-git , looking forward for your contribution!

**Comment by jfuss** [comment]
PR merged. This will go out with the next SAM CLI release. 

Closing.
