### ISSUE TITLE
Correct dotnet6 hello-step-functions-sample-app

### ISSUE THREAD

**Issue by ulili5** [aws/aws-sam-cli-app-templates#216]
The [dotnet6 hello-step-functions-sample-app](https://github.com/aws/aws-sam-cli-app-templates/tree/master/dotnet6/cookiecutter-aws-sam-hello-step-functions-sample-app) is not working as expected.

After deploying the project created from this template. If you try to test the project by running the AWS Step Functions state machine it is failing because all the 3 Lambda functions are returning empty JSON payload ```{}``` that's making the Step Functions state machine to fail.

The root cause is that all C# contract call have only filed they do not have proprieties meaning ```get; set;``` when the object is serialized it returns empty JSON ```{}```

**Comment by mingkun2020** [comment]
Thank you for your contribution! We really appreciate it. We will take time to review the pr.

**Comment by jfuss** [comment]
Closing. PR was merged and will be included in the next release of SAM CLI.
