### ISSUE TITLE
Quick Start Template for TypeScript Serverless APIs

### ISSUE THREAD

**Issue by allanchua101** [aws/aws-sam-cli-app-templates#225]
### Describe your idea/feature/enhancement

I wish SAM CLI offers the capability to automatically scaffold AWS Quick Start - serverless APIs for TypeScript.

### Proposal

Add a `nodejs14.x - TypeScript` option on `sam init` process for Quick Start templates of Serverless APIs.

**Comment by CoshUS** [comment]
Transferred to app template repo. 
@allanchua101 Would this PR be something you are looking for?
https://github.com/aws/aws-sam-cli-app-templates/pull/193

**Comment by mndeveci** [comment]
Thanks for your recommendation @allanchua101

We already have a Typescript template here: https://github.com/aws/aws-sam-cli-app-templates/tree/master/nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs

I am resolving this issue but please let us know if you are recommending something else.
