### ISSUE TITLE
Adding Tiered Compilation configuration to Java templates

### ISSUE THREAD

**Issue by msailes** [aws/aws-sam-cli-app-templates#234]
Tiered compilation for Java was discussed in the AWS Compute Blog [Optimizing AWS Lambda function performance for Java](https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/)

For the majority of use cases this can decrease cold start times by up to 60%. I think it would be good for customers to include this configuration in Java templates.

If approved I can write the PR required.

Thanks,

**Comment by mndeveci** [comment]
Thanks for raising this issue @msailes , I am resolving this now since the changes have been merged.
