### ISSUE TITLE
Bug: Rust template build failure

### ISSUE THREAD

**Issue by shinglyu** [aws/aws-sam-cli-app-templates#267]
### Description: 
When using the x86_64 architecture for the Rust template, the command `make build` fails.
The empty parameter `CARGO_LAMBDA_FLAGS=''` is not acceptable by `cargo lambda build`. I can help fix it but I'm not sure if we should remove the environment variable or try to make `cargo lambda` accept empty parameters.

### Steps to reproduce:
Create a SAM project using `sam init` and select the Rust template.

### Observed result:
```
$ make build
error: Found argument '' which wasn't expected, or isn't valid in this context

USAGE:
    cargo lambda build [OPTIONS]

For more information try --help
```

### Expected result:
`make build` should invoke `cargo lambda build --release` and finish successfully.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 18.04.6 LTS (on AWS Cloud9)
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.53.0
3. AWS region: eu-central-1

`Add --debug flag to any SAM CLI commands you are running`

**Comment by moelasmar** [comment]
thanks @shinglyu  for raising this issue. 
I think it is better to pass the target in all cases, and not to depend on the default behaviour, so I think the Makefile should be something like this:
```
{% if cookiecutter.architecture == 'arm64' -%}
CARGO_LAMBDA_FLAGS = aarch64-unknown-linux-gnu
{%- else -%}
CARGO_LAMBDA_FLAGS = x86_64-unknown-linux-gnu
{%- endif %}

.PHONY: build
build:
        cargo lambda build --release --target $(CARGO_LAMBDA_FLAGS)
```
