### ISSUE TITLE
Feature request: Replace unittest TestCase with Pytest in hello-python templates

### ISSUE THREAD

**Issue by hunt3ri** [aws/aws-sam-cli-app-templates#276]
### Describe your idea/feature/enhancement

The test code in cookiecutter-aws-sam-hello-python is a somewhat confusing mix of pytest and unittest tests.  I suggest we standardize on pytest and use fixtures in both the unit and integration tests.

eg

### Current Unit Tests
Are pytest flavour

```python
@pytest.fixture()
def apigw_event():
    """ Generates API GW Event"""

    return {
        "body": '{ "test": "body"}'
        ...
    }

def test_lambda_handler(apigw_event, mocker):
    ret = app.lambda_handler(apigw_event, "")

```

#### Current Integration Tests

Are unittest flavour
``` python
class TestApiGateway(TestCase):
    api_endpoint: str

     def setUp(self) -> None:
        ....

```

### Proposal

Standardize on pytest in the integration test examples within cookiecutter-aws-sam-hello-python across python 3.7, 3.8 and 3.9

### Additional Details

I'm happy to implement this if the community gives it a thumbs up

**Comment by jfuss** [comment]
@hunt3ri Can you be more specific. Looking at https://github.com/aws/aws-sam-cli-app-templates/blob/master/python3.7/cookiecutter-aws-sam-hello-python/%7B%7Bcookiecutter.project_name%7D%7D/tests/unit/test_handler.py they are using pytest.

**Comment by hunt3ri** [comment]
@jfuss sure.  The integration tests that the hello-world project generate use unittest setup approach, see below

[https://github.com/aws/aws-sam-cli-app-templates/blob/master/python3.9/cookiecutter-aws-sam-hello-python/%7B%7Bcookiecutter.project_name%7D%7D/tests/integration/test_api_gateway.py](https://github.com/aws/aws-sam-cli-app-templates/blob/master/python3.9/cookiecutter-aws-sam-hello-python/%7B%7Bcookiecutter.project_name%7D%7D/tests/integration/test_api_gateway.py)

While in the same template we use pytest.fixture to configure the test (see here)

[https://github.com/aws/aws-sam-cli-app-templates/blob/master/python3.9/cookiecutter-aws-sam-hello-python/%7B%7Bcookiecutter.project_name%7D%7D/tests/unit/test_handler.py](https://github.com/aws/aws-sam-cli-app-templates/blob/master/python3.9/cookiecutter-aws-sam-hello-python/%7B%7Bcookiecutter.project_name%7D%7D/tests/unit/test_handler.py)

This seems confusing and inconsistent to me, especially for beginners.  As they might draw the conclusion that we can't setup the integration test with pytest.

**Comment by jfuss** [comment]
The integration tests are for testing the cookiecutter (which I don't even know if we run anymore). So those are not shown to customer doing `sam init`. 

The team is also more comfortable with `unittest`, it's how all our repos are setup. So given pytest is only in the examples and the integrations are for the maintainers, I not inclined to change it.

**Comment by hunt3ri** [comment]
They definitely are shown, as I just ran `sam init` today on 1.55 and those precise tests were generated.

Those integration tests I linked to test the api_gateway the helloworld sam app generates via the cloudformation stack.  Unless I'm missing something fundamental here??

**Comment by jfuss** [comment]
@hunt3ri Nope you are right, my mistake. I got lost in the layout. 

I am fine with moving it all to `pytest`. Consistency within the examples are important.

**Comment by hunt3ri** [comment]
@jfuss ha no worries, getting people onto the same page is always tricky 😄 

OK I'll pull together a PR and you can let me know what you think.  I'm only going to worry about Python 3.7, 3.8, 3.9 as 3.6 is now not supported.  But let me know if you disagree.

Thanks for the support

**Comment by jfuss** [comment]
@hunt3ri Seems reasonable to me!

**Comment by hunt3ri** [comment]
Thanks for merging @jfuss 👍

**Comment by lucashuy** [comment]
Your changes are now live, thanks @hunt3ri for your contribution! Feel free to open a new issue if you have any more feedback

**Comment by hunt3ri** [comment]
Thanks @lucashuy happy to help 😄
