### ISSUE TITLE
Feature request: Remove Python 3.6 Templates

### ISSUE THREAD

**Issue by hunt3ri** [aws/aws-sam-cli-app-templates#280]
### Describe your idea/feature/enhancement

Python 3.6 is not supported by the Python community or AWS.  You can't create new lambdas using 3.6.  We should remove all 3.6 templates, as 3.6 is neither supported or secure.

This removes a maintenance burden and will reduce the overall size of the template package download

### Proposal

- Remove all python 3.6 templates
- Remove 3.6 references from manifests
- Remove 3.6 references from documentation
- Remove 3.6 references from Jupyter notebooks and replace with 3.7

### Additional Details

If community approves this request I'm happy to create the PR

**Comment by sriram-mv** [comment]
This is a great initiative, please go ahead and make a PR for this and you can reference this doc: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy while making the PR too

**Comment by lucashuy** [comment]
Thanks for your contributions! Closing as this is now live 😃
