### ISSUE TITLE
Bug: Build fails for "Hello World Example TypeScript w/ Lambda Powertools"

### ISSUE THREAD

**Issue by bpauwels** [aws/aws-sam-cli-app-templates#285]
### Description:
For the nodejs14.x template "Hello World Example TypeScript w/ Lambda Powertools" the `sam build` command fails with errors stating that the lambda powertools dependencies cannot be resolved.

```
[ERROR] Could not resolve "@aws-lambda-powertools/metrics"
[ERROR] Could not resolve "@aws-lambda-powertools/logger"
[ERROR] Could not resolve "@aws-lambda-powertools/tracer"
```

### Steps to reproduce:

Run `sam init`and create a new project with the nodejs14.x template "Hello World Example TypeScript w/ Lambda Powertools". Then run `sam build` in the project directory.

### Observed result:

Build fails with the errors mentioned above.

### Expected result:

Build succeeds.

**Comment by moelasmar** [comment]
thanks @bpauwels for your contribution.

**Comment by super132** [comment]
Closing as the PR was merged.
