### ISSUE TITLE
Feature request: Nodejs16.x support for "Hello World Example TypeScript w/ Lambda Powertools"

### ISSUE THREAD

**Issue by bpauwels** [aws/aws-sam-cli-app-templates#287]
### Describe your idea/feature/enhancement

Support Nodejs16.x runtime for the template "Hello World Example TypeScript w/ Lambda Powertools"

### Proposal

/

### Additional Details

/

**Comment by moelasmar** [comment]
Thanks @bpauwels for your contribution.

**Comment by mildaniel** [comment]
Closing as the corresponding PR has been merged.
