### ISSUE TITLE
Please generate tarball release

### ISSUE THREAD

**Issue by rluria14** [aws/aws-sam-cli-app-templates#29]
Please generate a tarball release for this repo. Thanks!

**Comment by awood45** [comment]
Good callout, we can definitely look into doing that.

**Comment by awood45** [comment]
Are there particular versioning issues driving this request, or do you just want the ability to also get this as a tarball?

For example, the `master` branch should always be usable, so the ZIP download link provided by GitHub, while not exactly what you're asking for, could meet your needs: https://github.com/awslabs/aws-sam-cli-app-templates/archive/master.zip

**Comment by rluria14** [comment]
No particular versioning issues, just need a tarball to build for conda-forge. 

Thanks!

**Comment by rluria14** [comment]
@awood45 any updates on this? thanks!

**Comment by oblute** [comment]
just bumping this @awood45 if it would be possible

**Comment by hoffa** [comment]
I'm not sure I understand the request. The `master` tarball is available at https://github.com/aws/aws-sam-cli-app-templates/archive/refs/heads/master.tar.gz.
