### ISSUE TITLE
Unable to clone on windows

### ISSUE THREAD

**Issue by shishirpy** [aws/aws-sam-cli-app-templates#303]
Unable to clone the repo on windows get the following error:

```
fatal: cannot create directory at 'provided.al2/graalvm/java11/cookiecutter-aws-sam-graalvm-gradle/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-core': Filename too long
warning: Clone succeeded, but checkout failed.
```

**Comment by hawflau** [comment]
Hi @shishirpy, thanks for raising the issue. Please enable Long Path in your Windows environment - https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html#install-sam-cli-instructions.

Closing as duplicated with https://github.com/aws/aws-sam-cli/issues/4031
