### ISSUE TITLE
Bug: Typescript Template:  esbuild-jest mocking is causing tests to fail

### ISSUE THREAD

**Issue by sukrit007** [aws/aws-sam-cli-app-templates#325]
### Description:

The typescript template uses esbuild-jest package,  which causes jest tests to fail if we add use jest mocks 
See  https://github.com/aelbore/esbuild-jest/issues/57

In addition,  this repo is no longer maintained. See https://github.com/aelbore/esbuild-jest/issues/69

### Steps to reproduce:

- Use sam init to initialize a Typescript hello world app using NodeJS 18
- Add jest.mock to your tests `jest.mock('@aws-sdk/client-dynamodb');`
- Test fails to run.

### Observed result:

`` Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    SyntaxError: /Users/sukrit007/git/intraedge/services/user-management/tests/unit/test-user-handler.test.ts: Cannot transform the imported binding "APIGatewayProxyEvent" since it's also used in a type annotation. Please strip type annotations using @babel/preset-typescript or @babel/preset-flow`

### Expected result:

Expect jest tests to work with mocking

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac 12.6.2
2. If using SAM CLI, `sam --version`:  SAM CLI, version 1.67.0
3. AWS region: us-east-2

`Add --debug flag to any SAM CLI commands you are running`

### Workaround
Replace esbuild-jest by https://github.com/ambar/es-jest  in following files 
- https://github.com/aws/aws-sam-cli-app-templates/blob/master/nodejs18.x/cookiecutter-aws-sam-hello-typescript-nodejs/%7B%7Bcookiecutter.project_name%7D%7D/hello-world/jest.config.ts#L8
- https://github.com/aws/aws-sam-cli-app-templates/blob/master/nodejs18.x/cookiecutter-aws-sam-hello-typescript-nodejs/%7B%7Bcookiecutter.project_name%7D%7D/hello-world/package.json#L22

**Comment by hawflau** [comment]
Hi @sukrit007, thanks for reporting the issue. Sounds like migrating to another library or implementing our own transformer is the way to go. We will prioritized it internally. Also feel free to contribute!

**Comment by sleepwithcoffee** [comment]
hi @hawflau should we use https://www.npmjs.com/package/ts-jest instead since it is more prevalently used?

**Comment by jfuss** [comment]
@sleepwithcoffee I am not familiar with the ts community. If that is most commonly used, happy to move to that package.

**Comment by qingchm** [comment]
This has been addressed in our most recent release 1.79.0 (https://github.com/aws/aws-sam-cli/releases/tag/v1.79.0). Closing the issue here. Thanks for the ticket!
