### ISSUE TITLE
Feature request: Python3.9 template for "Hello World Python w/ Lambda Powertools"

### ISSUE THREAD

**Issue by leandrodamascena** [aws/aws-sam-cli-app-templates#333]
### Describe your idea/feature/enhancement

Python3.9 template for "Hello World Python w/ Lambda Powertools"

### Proposal

Add details on how to add this to the product.

**Comment by mildaniel** [comment]
Thanks for the contribution! The team will work to review the pull request.

**Comment by hnnasit** [comment]
Thank you for your contributions @leandrodamascena! Closing as the PR is already merged and released.
