### ISSUE TITLE
Feature request: .NET 6 and .NET 7 templates for "Hello World .NET w/ Lambda Powertools"

### ISSUE THREAD

**Issue by sliedig** [aws/aws-sam-cli-app-templates#335]
### Describe your idea/feature/enhancement

Create Hello World Example .NET w/ Lambda Powertools templates for dotnet6 and aot.dotnet7 runtimes.

### Proposal

Create Hello World templates based off the existing `dotnet6` and `aot.dotnet7 (provided.al2)` templates that include AWS Lambda Powertools for .NET core utilities - logging, tracing and metrics

### Additional Details

https://github.com/awslabs/aws-lambda-powertools-dotnet

**Comment by mildaniel** [comment]
Thanks for the contribution! The team will work to review the pull request.
