### ISSUE TITLE
Feature request: Java8 and Java11 templates for "Hello World Java w/ Lambda Powertools"

### ISSUE THREAD

**Issue by am29d** [aws/aws-sam-cli-app-templates#337]
### Describe your idea/feature/enhancement

Create Hello World Example Java w/ Lambda Powertools templates for java8, java8.al2 and java11 runtimes, for maven and gradle build tools. 

### Proposal

Create Hello World templates based off the existing java8 and java8.al, java11 templates that include AWS Lambda Powertools for Java core utilities - logging, tracing and metrics

### Additional Details
https://github.com/awslabs/aws-lambda-powertools-java

**Comment by mildaniel** [comment]
Thanks for the contribution! The team will work to review the pull request.

**Comment by mndeveci** [comment]
This feature is merged and released with SAM CLI, resolving it.
