### ISSUE TITLE
Feature request: Nodejs18.x Template for "Hello World Example TypeScript w/ Lambda Powertools"

### ISSUE THREAD

**Issue by shdq** [aws/aws-sam-cli-app-templates#339]
### Describe your idea/feature/enhancement

Nodejs18.x template for "Hello World Example TypeScript w/ Lambda Powertools"

### Additional Details

Update `nodejs14.x` and `nodejs16.x` template dependencies and AWS Lambda Powertools packages.

**Comment by dreamorosi** [comment]
Maintainer of AWS Lambda Powertools for TypeScript here, I'm working with @shdq to get this PR up. This is part of the work being done with the other Powertools PR that are up right now.

**Comment by jfuss** [comment]
Seems reasonable. Mostly commenting to "ack" the request.

**Comment by hnnasit** [comment]
Thank you for your contributions @shdq. Closing this issue as the changes have been merged.
