### ISSUE TITLE
Go version:  `main_test.go` uses `ioutil.ReadAll`

### ISSUE THREAD

**Issue by wunderbarb** [aws/aws-sam-cli-app-templates#344]
The go code generated by `sam init -r go=1.x` uses `ioutil.ReadAll`.   This function is deprecated since go1.16 and should be replaced by `io.ReadAll`.

Still in 1.73.0

**Comment by lucashuy** [comment]
Hi, thanks for opening this issue. We'll see if we can get this function call updated. As a general callout, we'd also be willing to accept community contributions to update these method calls across our various golang templates.

**Comment by hnnasit** [comment]
Closing this issue as the changes have been merged and released in SAM CLI 1.75.0.
