### ISSUE TITLE
.NET and TypeScript aren't part of Hello World Example With Powertools group

### ISSUE THREAD

**Issue by heitorlessa** [aws/aws-sam-cli-app-templates#354]
Hey team, I've just upgraded to the latest SAM CLI (1.75) to try out the new Lambda Powertools examples, and noticed the .NET and TypeScript examples are not available under the Powertools group.

**Fix**: I dug into `manifest-v2.json` and found out that the `useCaseName` differs for .NET and TypeScript. I'm sending a corresponding PR to sync them up.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/3340292/221786668-51b34e10-dcf3-425c-8856-2f7f5bf874f4.png">

It is only available if I select the first option `Hello World Example`, and choose their respective runtime (.NET, NodeJS).

<img width="625" alt="image" src="https://user-images.githubusercontent.com/3340292/221783988-ac6bfe58-3b04-4ec2-ae28-9be9d98a0d95.png">

**Question**: Should we also bump Hello World With Powertools group (8) right next to the plain Hello World group (1)?

Thank you

**Comment by heitorlessa** [comment]
Gotcha!

**Comment by hnnasit** [comment]
Closing this issue as the new version of SAM CLI has been released with these changes https://github.com/aws/aws-sam-cli/releases/tag/v1.76.0.
