### ISSUE TITLE
Documentation: Removing `aws cloudformation delete-stack`

### ISSUE THREAD

**Issue by sleepwithcoffee** [aws/aws-sam-cli-app-templates#384]
We should remove the mentioning about `aws cloudformation delete-stack` and `aws cloudformation describe-stacks`.
We should direct users to use new CLIs `sam delete` and `sam list endpoints` instead.

**Comment by qingchm** [comment]
@sleepwithcoffee Really appreciate the improvement idea! This for sure makes sense and I will take a look at your PRs. Thanks in advance for contributing

**Comment by jfuss** [comment]
All the PRs are in queue to be merged. Going to mark this as waiting for release.

@sleepwithcoffee Thanks for reporting and taking the time to get everything updated!

**Comment by hnnasit** [comment]
Closing this issue as the changes were released in SAM CLI [1.81.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.81.0). Thanks @sleepwithcoffee for your contributions!
