### ISSUE TITLE
Feature request: Full stack web app

### ISSUE THREAD

**Issue by awsbenpeterson** [aws/aws-sam-cli-app-templates#399]
### Describe your idea/feature/enhancement

I wish SAM cli init quick start templates included an option for full stack web app that takes option 3 (Serverless API) and adds a front end, hosting and api gateway integration.

### Proposal

Add a nodejs18.x option on the sam init process for Quick Start templates that deploys a full stack web app.

### Additional Details

Also propose vue.js as the front-end framework

**Comment by lucashuy** [comment]
Thanks for opening this feature request! This is an interesting template idea, we'll have to bring this up to the team to discuss this further

**Comment by mildaniel** [comment]
The linked PR has now been merged and released. Closing.
