### ISSUE TITLE
Improve build & test by running pytest in multithread

### ISSUE THREAD

**Issue by sleepwithcoffee** [aws/aws-sam-cli-app-templates#417]
We have package `pytest-xdist` in our `requirements.txt` but in the pipeline definition, pytest is run in a single thread. To improve CI time, it is better to run in asynchronously.

Current script:
```
pytest -vvv tests/unit/
```

Can be updated to the following to run on all available CPU cores automatically:
```
pytest -n $(python -c "import psutil; print(psutil.cpu_count(logical=True))") -vvv tests/unit/
```

Notes:
* Additional `psutil` is required.
* Instead of detecting number of CPU cores automatically, we can also choose a fixed number. However, it will not be as optimized.
* Since all build/CI agents are supposed to be disposable, we can utilize all available CPU cores. However, another option is to use half the number of available cores to avoid blocking another process if any. Even though, I don't find this neccessary

**Comment by hnnasit** [comment]
Thanks @sleepwithcoffee for raising a PR to optimize the time for the test sets, I will review your PR.

**Comment by mndeveci** [comment]
Resolving this issue since the PR is been merged, thanks for your contribution!
