### ISSUE TITLE
Bug: s3-app with node 16 - sam local invoke fails with ACCESS DENIED

### ISSUE THREAD

**Issue by nkl3in** [aws/aws-sam-cli-app-templates#476]
### Description:
Following the instructions on the README, the steps to build and deploy both work, but the step to test locally using the prescribed command fails.

### Steps to reproduce:
After successful `sam build` and `sam deploy --guided`, enter the command to test locally, as described in the README:

```bash
my-application$ sam local invoke S3JsonLoggerFunction --event events/event-s3.json
```

### Observed result:
```
Invoking src/handlers/s3-json-logger.s3JsonLoggerHandler (nodejs16.x)
Local image is up-to-date
Using local image: public.ecr.aws/lambda/nodejs:16-rapid-x86_64.

Mounting /sam-examples/s3-app/.aws-sam/build/S3JsonLoggerFunction as /var/task:ro,delegated, inside runtime container
START RequestId: 53a44e6c-f044-4282-b14a-5698cd668d2c Version: $LATEST
2024-01-06T02:27:19.423Z	e5e52e73-c261-4bdc-b7f0-dab2134e823e	ERROR	Error calling S3 getObject: AccessDenied: Access Denied
```

### Expected result:
I would have not expected an error

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS
2. If using SAM CLI, `sam --version`:  SAM CLI, version 1.105.0
3. AWS region: us-east-1

`Add --debug flag to any SAM CLI commands you are running`

**Comment by nkl3in** [comment]
> Hi, do your local credentials have permissions to call the `GetObject` S3 API? The function makes an external API call to S3.

I think so, but maybe I'm missing something?

For my local credentials I am using an Identity Center user with 'AdministratorAccess', and I authenticate using SSO.  The same permissions allowed me to successfully execute the `sam deploy --guided` script, and I can see the S3 instance in the console when logged into the console as this same user.

**Comment by lucashuy** [comment]
That should all be fine then, just to double check, the `events/event-s3.json` file contains the bucket name that the function references. Is this changed to reflect the name that was set in guided? I was able to get to same error with the wrong bucket name.

**Comment by lucashuy** [comment]
The Lambda function is suppose to fetch an item from the bucket it creates. So if the bucket is empty, this function won't be doing anything useful. If you do have file(s) in the bucket, then changing the `Records[].s3.object` JSON object at the bottom of the event file to match the file that is uploaded to that bucket, then the function should be able to fetch the file.

**Comment by nkl3in** [comment]
Ok, yup, that did the trick.  Many thanks for the pointers.

From the perspective of someone new to the tool set, it would be helpful to have these additional steps spelled out more clearly in the README instructions.   Happy to help with that.
