### ISSUE TITLE
Bug: Duplicate Use Case "Hello World Example With Powertools for AWS Lambda"

### ISSUE THREAD

**Issue by Beau-Gosse-dev** [aws/aws-sam-cli-app-templates#485]
### Description:
In some template use case names the word `with` is capitalized causing duplicate powertool use case templates.
`Hello World Example with Powertools for AWS Lambda`
`Hello World Example With Powertools for AWS Lambda`

These 2 locations need to be changed to lowercase:

https://github.com/aws/aws-sam-cli-app-templates/blob/b2f83d35cfe79f4057149330ab73f7c1e929b2b1/manifest-v2.json#L1229

https://github.com/aws/aws-sam-cli-app-templates/blob/b2f83d35cfe79f4057149330ab73f7c1e929b2b1/manifest-v2.json#L1162

### Steps to reproduce:
Call `sam init`
Select `AWS Quick Start Templates` 

Output below (notice 3 and 15)

```
Choose an AWS Quick Start application template
        1 - Hello World Example
        2 - Data processing
        3 - Hello World Example with Powertools for AWS Lambda
        4 - Multi-step workflow
        5 - Scheduled task
        6 - Standalone function
        7 - Serverless API
        8 - Infrastructure event management
        9 - Lambda Response Streaming
        10 - Serverless Connector Hello World Example
        11 - Multi-step workflow with Connectors
        12 - GraphQLApi Hello World Example
        13 - Full Stack
        14 - Lambda EFS example
        15 - Hello World Example With Powertools for AWS Lambda
        16 - DynamoDB Example
        17 - Machine Learning
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows/Linux
2. If using SAM CLI, `sam --version`: 1.109.0 (Latest as of today)
3. AWS region: N/A

`Add --debug flag to any SAM CLI commands you are running`

**Comment by mildaniel** [comment]
Thanks for the heads-up @Beau-Gosse-dev. I can reproduce the issue and tagging as a bug.

**Comment by hnnasit** [comment]
Closing as the fix for this issue has been merged already.
