### ISSUE TITLE
Bug: Typo in the package.json for the nodejs20.x/hello-ts-pt template

### ISSUE THREAD

**Issue by cortexcompiler** [aws/aws-sam-cli-app-templates#502]
### Description:
There is a typo in the `package.json` for the `nodejs20.x/hello-ts-pt` template 

### Steps to reproduce:
Use `sam init` to generate a "3 - Hello World Example with Powertools for AWS Lambda" project and then try to run `npm i` and you will see it does not work.

The problem file is: [nodejs20.x/hello-ts-pt/{{cookiecutter.project_name}}/hello-world/package.json](https://github.com/aws/aws-sam-cli-app-templates/blob/master/nodejs20.x/hello-ts-pt/%7B%7Bcookiecutter.project_name%7D%7D/hello-world/package.json#L1)

### Observed result:
`npm i` fails with the following:
```
npm ERR! code EJSONPARSE
npm ERR! path /Users/bradmongeon/GIT/EXEMPLARS/example-serverless-typescript-api/hello-world/package.json
npm ERR! JSON.parse Unexpected non-whitespace character after JSON at position 1 while parsing near "2{0 3\"name\": \"hello_w..."
npm ERR! JSON.parse Failed to parse JSON data.
npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.
```

### Expected result:
`npm i` should install the dependencies

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
N/A

I have created the following PR to fix this:
https://github.com/aws/aws-sam-cli-app-templates/pull/501

**Comment by hnnasit** [comment]
Thanks @cortexcompiler for reporting the issue and raising a PR with the fix. You can also use `sam build` to build your project.

**Comment by cortexcompiler** [comment]
> Thanks @cortexcompiler for reporting the issue and raising a PR with the fix. The PR looks good to me. You can also use [sam build](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html) to build your project.

Thanks, I did generate and try the `sam build`.  The `npm install` was the shortest route to recreate the issue.

**Comment by cortexcompiler** [comment]
Fixed in this PR: https://github.com/aws/aws-sam-cli-app-templates/pull/501
