### ISSUE TITLE
Remove .NET 7 AOT template

### ISSUE THREAD

**Issue by Beau-Gosse-dev** [aws/aws-sam-cli-app-templates#506]
.NET 7 has reached end of life and has been removed from the Lambda docs. It should be removed from `sam init`. Users who would like to use AOT should use .NET 8 now.

**Comment by hnnasit** [comment]
Closing as the PR has been merged and released in [SAM CLI 1.121.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.121.0).
