### ISSUE TITLE
`sam init` fails because manifest.json not found

### ISSUE THREAD

**Issue by jpalmer37** [aws/aws-sam-cli-app-templates#507]
### Description:

I am running the SAM CLI, version 1.36.0. A simple `sam init` leads to the following error 

```
Which template source would you like to use?
1
...
Project name [sam-app]: 


Cloning from https://github.com/aws/aws-sam-cli-app-templates
Traceback (most recent call last):
...
  File "/Users/jpalmer/miniforge/envs/aws/lib/python3.8/site-packages/samcli/commands/init/init_templates.py", line 56, in prompt_for_location
    options = self.init_options(package_type, runtime, base_image, dependency_manager)
  File "/Users/jpalmer/miniforge/envs/aws/lib/python3.8/site-packages/samcli/commands/init/init_templates.py", line 120, in init_options
    return self._init_options_from_manifest(package_type, runtime, base_image, dependency_manager)
  File "/Users/jpalmer/miniforge/envs/aws/lib/python3.8/site-packages/samcli/commands/init/init_templates.py", line 124, in _init_options_from_manifest
    with open(str(manifest_path)) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jpalmer/.aws-sam/aws-sam-cli-app-templates/manifest.json'
```

Seems to be caused by the `manifest-v2.json` name. Not sure whether should be addressed here or on the SAM CLI GitHub. 

### Steps to reproduce:
Running `sam init` in a new repo. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOSX
2. If using SAM CLI, `sam --version`: 1.36.0
3. AWS region: us-east-1

**Comment by hnnasit** [comment]
Hi @jpalmer37, SAM CLI has updated this repo quite a lot since the SAM CLI version 1.36.0. The latest SAM CLI version is 1.120.0. Can you try installing this latest version and check if you still run into issues? You can check the installation [doc](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html) for more info.

**Comment by jpalmer37** [comment]
Hi @hnnasit, sorry about that oversight. I was simply pulling the latest from the conda-forge channel (1.36.0), thinking it might be up to date. I'll install the true latest and give it a run. Thank you!

**Comment by jpalmer37** [comment]
Not a valid issue in latest version.
