### ISSUE TITLE
Bug: hello-img and apigw-scikit projects for python3.13 using old dependencies

### ISSUE THREAD

**Issue by hnnasit** [aws/aws-sam-cli-app-templates#518]
### Description:

The `hello-img` project for python3.13 Dockerfile uses `python3.12` instead of `python3.13` [here](https://github.com/aws/aws-sam-cli-app-templates/blob/master/python3.13/hello-img/%7B%7Bcookiecutter.project_name%7D%7D/hello_world/Dockerfile#L1).

The `scikit` project uses the old `scikit` dependency which does not support `python3.13` [here](https://github.com/aws/aws-sam-cli-app-templates/blob/master/python3.13/apigw-scikit/cookiecutter.json#L3).

### Expected result:

Dockerfile should use `3.13` instead of `3.12` for sam build to work.
scikit dependency should be bumped to `1.5.2` for python3.13 project builds to work.

**Comment by mndeveci** [comment]
Released with latest SAM CLI
