### ISSUE TITLE
Please add a working Rust app template

### ISSUE THREAD

**Issue by brainstorm** [aws/aws-sam-cli-app-templates#54]
Mirroring issue https://github.com/aws/aws-lambda-builders/issues/167#issuecomment-698100365 here.

The official works and general support are not exactly helpful at the time of writing this, unfortunately, so hopefully those pointers help for the time being? :/

**Comment by npajkovsky** [comment]
I'd like to have rust support as well.

**Comment by jfuss** [comment]
We don't have any default builders but maybe we can enabling the building through `Makefile` builders or using Lambda Images over zips? 

I am no expert in Rust, but happy to review a PR from the community on this.

**Comment by brainstorm** [comment]
Sure, let's get this testing and review process going over https://github.com/aws/aws-sam-cli-app-templates/pull/129 ?

**Comment by brainstorm** [comment]
Nevermind, the AWS Rust team is doing a great job with `cargo-lambda`, SAM is not strictly needed anymore, AFAICT.
