### ISSUE TITLE
support CodeBuild buildspec.yml v0.2

### ISSUE THREAD

**Issue by mbacchi** [aws/aws-sam-cli-app-templates#55]
In the [CodeBuild buildspec reference](https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-versions) it indicates that `type: zip` is deprecated as of `v0.2`.

This [cookiecutter buildspec](https://github.com/aws/aws-sam-cli-app-templates/blob/master/nodejs12.x/cookiecutter-quick-start-web/%7B%7Bcookiecutter.project_name%7D%7D/buildspec.yml#L20) should not reference `type: zip`

**Comment by jfuss** [comment]
Good catch @mbacchi. Updating labels.
