### ISSUE TITLE
Add TypeScript examples to the NodeJs templates

### ISSUE THREAD

**Issue by scionwest** [aws/aws-sam-cli-app-templates#76]
## What is this?
This issue is to track the work I am doing in a fork to add a TypeScript NodeJS example template. The TypeScript template should include the following items:

- Handlers and all function code in TypeScript
- Unit Tests written in TypeScript
- Example code for mocking dependencies in tests.
- Scaffolding for an API Gateway based function
- Linting integration
- Successful Transpilation to JavaScript

The template is built, tested and has been deployed into my AWS environment without issues. I'm not ready to start the process of issuing a pull request back to this repository.

## Guidance

I searched for documentation on contributing templates and wasn't able to find much to help me meet the AWS teams expectations for what a template should consist of. I have the following questions I'd appreciate some guidance to help me prepare for the pull request.

1. The template is an API Gateway based template. Is a `post` and `get-by-id` handler example sufficient or do I need more HTTP methods?
2. How should the template be named? At the moment I have called it `cookiecutter-typescript-app-template` and it resides within the `nodejs12.x` directory. I see there is a `nodejs.x-image` directory but I am unsure of what that directory represents and if I need to support it.
3. I built this for the nodejs12.x runtime. Do I have to build a version for the nodejs10.x runtime? If so, can it be done as a separate PR?

I will submit my pull request this evening and reference this issue in the PR.

Thanks!

**Comment by scionwest** [comment]
When I run `$ sam init --location /path/to/template.zip --runtime nodejs12.x --name foobar` the CLI still prompts me to confirm/select the runtime and project name. When I do this however without the `location` switch it works as expected - I select a template from the existing list and it generates the project.

Does this process not work when you add the `--location` switch or is there something I'm missing in a manifest file or something someplace?

I'm also unclear if I should be asking these questions on this issue, or in the PR itself.

**Comment by mndeveci** [comment]
Hi @scionwest ,

With esbuild support in SAM CLI, we have included some TS examples in the application templates. I am resolving this issue for now but we would be happy to review a PR if you want to contribute more to TS examples.

Thanks!
