### ISSUE TITLE
Request for Documentation on creating custom template repository and templates

### ISSUE THREAD

**Issue by rgoodwin** [aws/aws-sam-cli-app-templates#81]
When launching `sam init` it gives you the ability to build from custom templates in a custom repository. Is there documentation (or pointers) on how to set that up and write the custom templates. (It looks like they are cookie cutter underneath; however some docs would help.

Generally, my team would like to be able to generate lambda projects from basic standard. -Thanks

**Comment by torresxb1** [comment]
Closing as there hasn't been more information provided. Please reopen if you can provide us with more information on what improvements we should make.
